[build-system]
requires = ["setuptools>=74.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "homozip"
description = "The mismatch-limited zipper: a minimal stochastic model of homology search"
dynamic = ["version", "dependencies"]
readme = "README.md"
license = {text = "GPLv3"}
authors = [
    {name = "Nicolas Mendiboure", email = "nicolas.mendiboure@ens-lyon.fr"}
]
classifiers = [
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Operating System :: Unix",
    "Operating System :: MacOS"
]
requires-python = "~=3.12"

[project.urls]
Homepage = "https://github.com/nmendiboure/homozip"

[project.scripts]
homozip = "homozip.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = {attr = "homozip.__version__"}
dependencies = {file = "requirements.txt"}

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
